### ISSUE TITLE
inventory_local returning an error on nbox_config dictionary

### ISSUE THREAD

**Issue by cdot65** [tbotnz/netpalm-admin#16]
default inventory_local.json file, only change was to config.json, where I pointed to inventory_local.json

```
setting netpalm_server to 10.0.2.15
setting netpalm_server_port to 9000
setting netpalm_api_key to 2a84465a-cf38-46b2-9d86-b84Q7d57f288
Traceback (most recent call last):
  File "netpalm-admin.py", line 10, in <module>
    conf = Config()
  File "/home/cremsburg/netpalm-admin/backend/confload/confload.py", line 30, in __init__
    self.inventory = self.get_inventory()
  File "/home/cremsburg/netpalm-admin/backend/confload/confload.py", line 55, in get_inventory
    token = nbox_config["netbox_token"]
TypeError: list indices must be integers or slices, not str
```

**Comment by tbotnz** [comment]
for local inventory ensure config.json has the following lines

    "inventory_type": "local",
    "inventory_file": "inventory_local
